### PR TITLE
prepend common >= 5 letter words

### PR DESCRIPTION
**Pull request by Konfekt**
This addresses https://github.com/girishji/ngram-complete.vim/issues/2

Well, my list of words with at least five letters doesn't have Google's frequencies but is sorted roughly according to frequency though I'm wondering why, say, million is so common.
Unfortunately, I'll have to dig to find out which word list served as source.

As as an aside, what's the point of completing shorter, say one-letter words such as `i` ?

### CODE REVIEW

**Comment by girishji** [comment]
Thanks! Also, there is an option called `triggerWordLen` in VimComplete that can be set to 2 or 3.
`

**Comment by girishji** [comment]
You made sure there are no duplicates, right?

**Comment by Konfekt** [comment]
It's been a few years, but yes, I checked again

**Comment by girishji** [comment]
I added 'triggerWordLen' specific to this.

**Pull request merged**
